baseURL = "https://mollybslp.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
theme = "hugo-scroll"
title = "Molly Brown - SLP"
[params]
description = "Molly Brown SLP"
favicon = "images/favicon.png"
images = ["images/cover-image.jpg"]
title = "Molly Brown SLP"
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
